version: '3.9'

services:
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_PASSWORD=An0thrS3crt
      - MYSQL_USER=citizix_user
      - MYSQL_DATABASE=citizix_db

  es:
    image: elasticsearch:8.4.0
    environment:
    - discovery.type=single-node
    - xpack.security.enabled=false
    ports:
      - 9200:9200

  app:
    build: .
    volumes:
      - .:/django
      - static_volume:/django/staticfiles
    expose:
      - 8000
    image: app:django
    container_name: django_container
    command:  bash -c "python3 manage.py collectstatic --noinput --clear && gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - mysql
      - es
      - redis

  # crowler:
  #   build: .
  #   volumes:
  #     - .:/django

  #   image: app:django
  #   container_name: crowler_task
  #   command:  bash -c "python3 getall.py"
  #   depends_on:
  #     - app

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"

  celery:
    build: .
    command: celery -A core worker --loglevel=INFO --concurrency=1
    volumes:
      - .:/django
    depends_on:
      - mysql
      - es
      - redis
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"

  celery-beat:
    build: .
    command: celery -A core beat --loglevel=INFO
    volumes:
      - .:/django
    depends_on:
      - mysql
      - es
      - redis
      - celery
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/django/staticfiles
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  static_volume: