# Generated by Django 3.2.3 on 2022-07-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uznews', '0002_auto_20220715_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
